### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheButterbrotMan** [Klyser8/Earthbounds#1] opened 2022-01-30 17:44 UTC
[crash-2022-01-30_14.12.51-server.txt](https://github.com/Klyser8/Earthbounds/files/7966510/crash-2022-01-30_14.12.51-server.txt)

**Comment by Klyser8** [comment] 2022-01-30 18:52
It looks like the "step height entity attribute" mod may have something to do with this issue.

Can you tell me how I can reproduce it?

**Comment by TheRanker** [comment] 2022-01-30 20:02
I don't use that mod so it's a dependency. Also this 

https://github.com/emilyploszaj/step-height-entity-attribute/issues/3

**Comment by Klyser8** [comment] 2022-01-30 20:11
What is the mod a dependency of? The error points to Minecraft's line of code, which confuses me quite a bit.

If I had to guess, the mod is somehow not compatible with other mods that introduce mobs?

**Comment by TheRanker** [comment] 2022-01-30 20:17
Never had an issue till I added ur mod to my pack . So I removed it and continued on with my pack dev. I'm not at pc currently to do it again with details

**Comment by Klyser8** [comment] 2022-01-30 20:19
Yeah, sorry to hear that :(
Though since its an issue that happens with other mobs from other mods from
what i can see, I'm afraid i cant do much about this unless you also report
it to the devs of that mod.

**Comment by TheButterbrotMan** [comment] 2022-01-30 20:19
I will provide another crashlog, give me some minutes.

**Comment by Klyser8** [comment] 2022-01-30 20:30
Alright! Thank you :)

**Comment by TheRanker** [comment] 2022-01-30 21:01
maybe you could contact that mod dev and work together to resolve it since it is clearly between yours and his.. and i have 300 mods.. and butterbotr has 600 mods.. never happened till we added yours.. so there may be a implemention of a mixin that isnt being used correct somewhere.

the other github i posted, i don thave their issues. but same type of crash.

**Comment by Klyser8** [comment] 2022-01-30 21:03
I've contacted them, I'll close the issue once it's resolved.

**Comment by TheButterbrotMan** [comment] 2022-01-30 21:04
https://bytebin.lucko.me/IZbIygbeb8

**Comment by Klyser8** [comment] 2022-01-31 01:00
https://github.com/emilyploszaj/step-height-entity-attribute/issues/4

The issue should be resolved. Thank you!

**Closed by Klyser8** 2022-01-31 01:00 UTC
Labels: crash

**Comment by Klyser8** [comment] 2022-02-01 15:22
This issue has been fixed in the most recent version of StepHeightEntityAttribute, however since BetterAnimalsPlus has not updated to that new version Earthbounds and BetterAnimalsPlus won't be compatible.

Hopefully BetterAnimalsPlus updates the version of StepHeightEntityAttribute soon!

**Comment by Sunconure11** [comment] 2022-02-08 09:52
I’m still getting this on 1.0.2

**Comment by Sunconure11** [comment] 2022-02-08 09:53
@Klyser8 

https://github.com/Klyser8/Earthbounds/issues/4

**Comment by Klyser8** [comment] 2022-02-08 10:47
According to StepHeightEntityAttribute's author the issue should have been fixed in their mod's most recent version. I'll see if I can do anything about this myself as it is an issue that's been affecting the mod for a week now

**Comment by Sunconure11** [comment] 2022-02-08 11:39
Where can one get this build? Because it is clearly not out yet.

**Comment by Klyser8** [comment] 2022-02-08 11:57
Updated Earthbounds to 1.0.3, it SHOULD have fixed the incompatibility issue... Though I don't understand why the dev didn't update their mod first (It's one line of code). Closed and resolved!
